### PR TITLE
 test page completed

### PR DESCRIPTION
**Pull request by paveltyk**

### CODE REVIEW

**Comment by nullhook** [comment]
Hey!

Here are my comments to begin with:

image 
image
1. The sections above should be one row and not separate rows. Divs are common but I think we should start using more of HTML5 semantics. Partitioning this view into `<section></section>` would make more sense
2. Why are the fonts blurry? Do we need to set the font-smoothing to antialiasing?

**Comment by AndreiBibik89** [comment]
Hello!

I've changed the code according to the review. I hope I correctly understood your's comments.

**Comment by nullhook** [comment]
Hey Bibik,

image

The image above should be one section including the title for "Order details" 

image
image

This type is being used twice so it's better to make a generic style. If you want to add margin bottom to one of them then it should be unique to that section only.

.table-col h3 and .request-completed p should have the same style treatment. 

image
the "CK" was hidden and is a typo. I guess you directly copy pasted from the PSD :) 

Question: Do you know how to work with Styleguides?

**Comment by AndreiBibik89** [comment]
Fixed.

I don't understand the question.. Just write the code according to the guides. Or what do you want to say?

**Pull request merged**
